# Generated by Django 4.2 on 2026-09-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField()),
                ('dead_line', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='in_progress', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
