# Generated by Django 6.0.7 on 2026-07-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField(blank=True)),
            ],
        ),
    ]
